services:
  postgres:
    image: postgres:15-alpine
    container_name: food_planner_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: food_planner_server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - PORT=${SERVER_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

  client:
    build: ./client
    container_name: food_planner_client
    ports:
      - "${CLIENT_PORT}:5174"
    environment:
      - VITE_API_URL=http://server:${SERVER_PORT}
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  pgdata:
